version: "3"
services:
  backend:
    build:
      context: .
    depends_on:
      - database
      - cache
  database:
    image: mariadb:10
    ports:
      - "3306:3306"
    environment:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_RANDOM_ROOT_PASSWORD
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
