apiVersion: apps/v1
kind: Deployment
metadata:
  name: egs-legacy-backend
  namespace: egs-legacy-staging
  labels:
    app: egs-legacy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egs-legacy-backend
  template:
    metadata:
      labels:
        app: egs-legacy-backend
    spec:
      containers:
      - name: egs-legacy-backend
        image: 017964463726.dkr.ecr.us-west-1.amazonaws.com/egs-legacy-backend:latest
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: egs-legacy-staging-secret
          - configMapRef:
              name: egs-legacy-staging-config
