apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: egs-legacy-backend-hpa
  namespace: egs-legacy-staging
  labels:
    app: egs-legacy-backend
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: egs-legacy-backend
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
